code --install-extension 42Crunch.vscode-openapi
code --install-extension ban.spellright
code --install-extension be5invis.vscode-custom-css
code --install-extension CADENAS.vscode-glsllint
code --install-extension chrmarti.ssh
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dbankier.vscode-quick-select
code --install-extension eiminsasete.apacheconf-snippets
code --install-extension felixfbecker.php-intellisense
code --install-extension golang.go
code --install-extension Gruntfuggly.todo-tree
code --install-extension hoovercj.vscode-power-mode
code --install-extension iampeterbanjo.elixirlinter
code --install-extension imperez.smarty
code --install-extension jakebathman.mysql-syntax
code --install-extension JakeBecker.elixir-ls
code --install-extension juanmnl.vscode-theme-1984
code --install-extension kleber-swf.unity-code-snippets
code --install-extension markis.code-coverage
code --install-extension mjmcloug.vscode-elixir
code --install-extension mrmlnc.vscode-apache
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension neilding.language-liquid
code --install-extension Nixon.env-cmd-file-syntax
code --install-extension oderwat.indent-rainbow
code --install-extension redhat.vscode-yaml
code --install-extension RobbOwen.synthwave-vscode
code --install-extension s-nlf-fh.glassit
code --install-extension slevesque.shader
code --install-extension softwaredotcom.swdc-vscode
code --install-extension sumneko.lua
code --install-extension Tim-Koehler.helm-intellisense
code --install-extension timonwong.shellcheck
code --install-extension Tobiah.unity-tools
code --install-extension WakaTime.vscode-wakatime
